### PR TITLE
Workaround for Cover Art Archive API returning HTML instead of JSON

### LINKED ISSUE #1024: AlbumArtArchive API does not return valid json for releases that lack art.
When fetching release covers, if a given release lacks any sort of album art it will throw the following error.

```
Failed to fetch front: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5738:19)
    at successSteps (node:internal/deps/undici/undici:5719:27)
    at fullyReadBody (node:internal/deps/undici/undici:4609:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async consumeBody (node:internal/deps/undici/undici:5728:7)
    at async CoverArtArchiveApi.getCovers (file:///Users/arc/Repos/github/arcanedisgea/art-example/node_modules/.pnpm/musicbrainz-api@0.20.0/node_modules/musicbrainz-api/lib/coverartarchive-api.js:45:22)
    at async getAlbumArt (file:///Users/arc/Repos/github/arcanedisgea/art-example/src/musicbrainz/api.js:37:21)
    at async file:///Users/arc/Repos/github/arcanedisgea/art-example/src/index.js:24:1
```

### Example Code:
```js
import { CoverArtArchiveApi } from "musicbrainz-api";

const aaClient = new CoverArtArchiveApi();

async function getArt(id) {
    try {
        const coverInfo = await aaClient.getReleaseCovers(
            id
        );
        console.log(coverInfo);
    } catch (error) {
        console.error(error);
    }
}

let working = "51765f03-6ff5-44e2-953d-edab1cb419c2"
let notWorking = "a8d5bd1b-e325-462d-af75-13ff94353102"

await getArt(working)
await getArt(notWorking)
```

Not working: https://coverartarchive.org/release/a8d5bd1b-e325-462d-af75-13ff94353102
Working: https://coverartarchive.org/release/51765f03-6ff5-44e2-953d-edab1cb419c2

Ultimately I think this is on the API to fix but if they cannot then the library should handle it more gracefully.

### PR DESCRIPTION
**Pull request by Haschikeks**
This should better handle the problem of getting html instead of json when requesting a cover art that does not exist.

It now returns:
```json
{
    "error": "Not Found",
    "help": "For usage, please see: https://musicbrainz.org/development/mmd"
}
```

Closes #1024

### CODE REVIEW

**Review by Borewit — CHANGES_REQUESTED** [review]
In addition to the HTTP response code (404), I propose to only send our own JSON in case the content-type of the response is HTML.

Maybe add a unit tests. 
In addition to test your JSON workaround, it is useful to add an _expected failure test_.

A test which is testing Cover Art Archive API, the cause of the issue, which now expects the HTML to be returned, and which shall fail of JSON is returned. Such a test can be used as a reminder, to remove the workaround, when Cover Art Archive API fixes the return type.

File: lib/coverartarchive-api.ts [hunk 1]
```diff
@@ -37,6 +37,15 @@ export class CoverArtArchiveApi {
         Accept: "application/json"
       }
     });
+
+    const contentType = response.headers.get("Content-Type");
+    if (contentType?.toLowerCase() !== "application/json" && response.status === 404) {
```
Comment (Borewit) [inline lib/coverartarchive-api.ts:42]:
```suggestion
    if (response.status === 404 && contentType?.toLowerCase() !== "application/json") {
```
If you turn the conditions around, this combined expression is much faster.

**Review by Borewit — CHANGES_REQUESTED** [review]
Awesome, minor suggested added

**Review by Borewit — APPROVED** [review]
Thanks @Haschikeks

**Comment by Borewit** [comment]
Part of [v0.20.1](https://github.com/Borewit/musicbrainz-api/releases/tag/v0.20.1)
